<?php

namespace common\models;

use function foo\func;
use Yii;
use backend\models\Adminuser;
use yii\helpers\Html;

/**
 * This is the model class for table "post".
 *
 * @property int $id
 * @property string $title
 * @property string $label_img
 * @property string $content
 * @property string $tags
 * @property string $avatar
 * @property int $status
 * @property int $create_time
 * @property int $update_time
 * @property int $author_id
 * @property int $cat_id
 *
 * @property Comment[] $comments
 * @property Adminuser $author
 * @property Poststatus $status0
 */
class Post extends \yii\db\ActiveRecord
{
    private $_oldTags;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'post';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title', 'content', 'status', 'author_id'], 'required'],
            [['content','label_img', 'tags'], 'string'],
            [['status', 'create_time', 'update_time', 'author_id','cat_id'], 'integer'],
            [['title'], 'string', 'max' => 128],
            [['author_id'], 'exist', 'skipOnError' => true, 'targetClass' => Adminuser::className(), 'targetAttribute' => ['author_id' => 'id']],
            [['status'], 'exist', 'skipOnError' => true, 'targetClass' => Poststatus::className(), 'targetAttribute' => ['status' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => '标题',
            'label_img' => '缩略图',
            'content' => '内容',
            'tags' => '标签',
            'status' => '状态',
            'create_time' => '创建时间',
            'update_time' => '更新时间',
            'author_id' => '作者',
            'cat_id' => '栏目',
            'avatar'=>'可选多张图片'
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */

    public function getAvatar(){
        return $this->hasMany(Avatar::className(),['post_id'=>'id']);
    }

    public function getComments()
    {
        return $this->hasMany(Comment::className(), ['post_id' => 'id']);
    }

    public function getActiveComments()
    {
        return $this->hasMany(Comment::className(), ['post_id' => 'id'])
            ->where('status=:status',[':status'=>2])->orderBy('id DESC');
    }
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAuthor()
    {
        return $this->hasOne(Adminuser::className(), ['id' => 'author_id']);
    }

    public function getCat()
    {
        return $this->hasOne(Cats::className(),['id'=>'cat_id']);
    }
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStatus0()
    {
        return $this->hasOne(Poststatus::className(), ['id' => 'status']);
    }

    public function beforeSave($insert)
    {

        if(parent::beforeSave($insert))
        {
            if($insert)
            {
                $this->create_time = time();
                $this->update_time = time();
                //$this->author_id = Yii::$app->user->id;
                //$this->status = 1;
            }
            else
            {
                $this->update_time = time();
            }
            return true;
        }else{
            return false;
        }

    }

    public function afterFind()
    {
        parent::afterFind(); // TODO: Change the autogenerated stub
        $this->_oldTags = $this->tags;
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
        Tag::updateFrequency($this->_oldTags,$this->tags);
    }

    public function afterDelete()
    {
        parent::afterDelete(); // TODO: Change the autogenerated stub
        Tag::updateFrequency($this->tags,'');
    }

    public function getUrl()
    {
        return Yii::$app->urlManager->createUrl([
            'post/detail',
            'id'=>$this->id,
            //'title'=>$this->title,
        ]);
    }

    public function getBeginning($length=288)
    {
        $tmpStr = strip_tags($this->content);
        $tmpLen = mb_strlen($tmpStr);
        $tmpStr = mb_substr($tmpStr,0,$length,'utf-8');
        return $tmpStr.($tmpLen>$length?'...':'');
    }

    public function getTagLinks()
    {
        $links = array();
        foreach(Tag::string2array($this->tags) as $tag)
        {
            $links[]= Html::a(Html::encode($tag),array('post/index','PostSearch[tags]'=>$tag));
        }

        return $links;
    }

    public function getCommentCount()
    {
        return Comment::find()->where(['post_id'=>$this->id,'status'=>2])->count();
    }

    public function fields()
    {
       return [
           'id',
           'title',
           'content'=>function($model){
                return $model->content = $this->getBeginning(20);
           },
           'status'=>function($model){
                return $model->status = $this->status0->name;
           },
           'author_id'=>function($model){
               return $model->author_id = $this->author->username;
           },
           'label_img',

       ];
    }
}
